<?xml version="1.0" encoding="iso-8859-1"?>
<chordlivesong>
    <title><![CDATA[I Want to Hold Your Hand]]></title>
    <artist><![CDATA[Beatles]]></artist>
    <keywords>
	<keyword><![CDATA[I Wanna Hold Your Hand]]></keyword>
    </keywords>
    <lines>
      <line kind="line">
	<chords>C  D    C  D    C  D</chords>
      </line>
      <line kind="space"/>
      <line kind="line">
	<chords>G                      D</chords>
	<lyrics><![CDATA[Oh yeah I'll tell you somenthing]]></lyrics>
      </line>
      <line kind="line">
	<chords>Em                   B</chords>
	<lyrics><![CDATA[I think you'll understand]]></lyrics>
      </line>
      <line kind="line">
	<chords>G                   D</chords>
	<lyrics><![CDATA[When I say that something]]></lyrics>
      </line>
      <line kind="line">
	<chords>Em                   B</chords>
	<lyrics><![CDATA[I want to hold your hand]]></lyrics>
      </line>
      <line kind="space"/>
      <line kind="line">
	<chords>C         D         G     Em</chords>
	<lyrics><![CDATA[I want to hold your hand]]></lyrics>
      </line>
      <line kind="line">
	<chords>C         D         G</chords>
	<lyrics><![CDATA[I want to hold your hand]]></lyrics>
      </line>
    </lines>
</chordlivesong>
